config/routes.rb
Fluctus::Application.routes.draw do

  #Institution Routes
  institution_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)/
  get 'institutions/', to: 'institutions#index', as: :institutions
  post 'institutions/', to: 'institutions#create'
  get 'institutions/new', to: 'institutions#new', as: :new_institution
  patch 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  put 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  delete 'institutions/:institution_identifier', to: 'institutions#destroy', institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier/edit', to: 'institutions#edit', as: :edit_institution, institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier', to: 'institutions#show', as: :institution, institution_identifier: institution_ptrn
  get 'events/:institution_identifier', to: 'events#index', as: :institution_events, institution_identifier: institution_ptrn

  #Intellectual Object Routes
  object_identifier_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.]+/
  get 'objects/:institution_identifier', to: 'intellectual_objects#index', as: :institution_intellectual_objects, institution_identifier: institution_ptrn
  post 'objects/:institution_identifier', to: 'intellectual_objects#create', institution_identifier: institution_ptrn
  get 'objects/*intellectual_object_identifier', to: 'intellectual_objects#show', as: :intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  patch 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  put 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  delete 'objects/*intellectual_object_identifier', to: 'intellectual_objects#destroy', intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/edit', to: 'intellectual_objects#edit', as: :edit_intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/restore', to: 'intellectual_objects#restore', as: :intellectual_object_restore, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/dpn', to: 'intellectual_objects#dpn', as: :intellectual_object_dpn, intellectual_object_identifier: object_identifier_ptrn
  get 'events/*intellectual_object_identifier', to: 'events#index', as: :intellectual_object_events, intellectual_object_identifier: object_identifier_ptrn
  post 'events/*intellectual_object_identifier', to: 'events#create', intellectual_object_identifier: object_identifier_ptrn

  #Generic File Routes
  file_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.\/]+/
  get 'files/*intellectual_object_identifier', to: 'generic_files#index', as: :intellectual_object_files, intellectual_object_identifier: object_identifier_ptrn
  post 'files/*intellectual_object_identifier', to: 'generic_files#create', as: :intellectual_object_generic_files, intellectual_object_identifier: object_identifier_ptrn
  get 'files/*generic_file_identifier', to: 'generic_files#show', as: :generic_file, generic_file_identifier: file_ptrn
  patch 'files/*generic_file_identifier', to: 'generic_files#update', generic_file_identifier: file_ptrn, trailing_slash: true, format: 'json'
  delete 'files/*generic_file_identifier', to: 'generic_files#destroy', generic_file_identifier: file_ptrn
  get 'events/*generic_file_identifier', to: 'events#index', as: :generic_file_events, generic_file_identifier: file_ptrn
  post 'events/*generic_file_identifier', to: 'events#create', generic_file_identifier: file_ptrn

  devise_for :users

  resources :users do
    patch 'update_password', on: :collection
    get 'edit_password', on: :member
    patch 'generate_api_key', on: :member
  end

  get 'users/:id/admin_password_reset', to: 'users#admin_password_reset', as: :admin_password_reset_user

  get '/itemresults/search', to: 'processed_item#search', as: :processed_item_search
  post '/itemresults/search', to: 'processed_item#search'
  get 'itemresults/', to: 'processed_item#index', as: :processed_items
  get 'itemresults/:id', to: 'processed_item#show', as: :processed_item
  post '/itemresults/review_all', to: 'processed_item#review_all'
  post '/itemresults/handle_selected', to: 'processed_item#handle_selected', as: :handle_selected
  post '/itemresults/show_reviewed', to: 'processed_item#show_reviewed'

  #delete 'itemresults/:etag/:name', to: 'processed_item#destroy'


  # ----------------------------------------------------------------------
  # These routes are for the API. They allow for more liberal identifier patterns.
  # Intel Obj identifier pattern includes dots. Intel Obj id pattern does not. Same for Generic File identifiers.
  # E.g. Obj Identifier = "virginia.edu.sample_bag"; Obj Id = "28337" or "urn:mace:aptrust:28337"
  # File Identifier = "virginia.edu.sample_bag/data/file.pdf"; File Id = "28999" or "urn:mace:aptrust:28999"
  #
  # Some of these routes are named because rspec cannot find them unless we explicitly name them.
  #

  post '/api/v1/itemresults/', to: 'processed_item#create', format: 'json', as: :processed_item_api_create
  get '/api/v1/itemresults/search', to: 'processed_item#api_search', format: 'json', as: :processed_item_api_search
  get '/api/v1/itemresults/ingested_since/:since', to: 'processed_item#ingested_since', as: :processed_items_ingested_since
  get '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#show', as: :processed_item_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  put '/api/v1/itemresults/:id', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_id
  put '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  get '/api/v1/itemresults/items_for_restore', to: 'processed_item#items_for_restore', format: 'json', as: :processed_item_api_restore
  get '/api/v1/itemresults/items_for_dpn', to: 'processed_item#items_for_dpn', format: 'json', as: :processed_item_api_dpn
  get '/api/v1/itemresults/items_for_delete', to: 'processed_item#items_for_delete', format: 'json', as: :processed_item_api_delete
  # This route must come after all other /api/v1/itemresults routes
  # because it's so general, it will catch everything.
  get '/api/v1/itemresults/:id', to: 'processed_item#api_show', format: 'json', id: /\d+/, as: :processed_item_api_show

  post '/api/v1/itemresults/restoration_status/:object_identifier', to: 'processed_item#set_restoration_status', as: :item_set_restoration_status, object_identifier: /.*/
  post '/api/v1/itemresults/delete_test_items', to: 'processed_item#delete_test_items', format: 'json', as: :processed_item_test_delete

  get '/api/v1/institutions/:institution_identifier', to: 'institutions#show', format: 'json', as: :institution_api_show, institution_identifier: institution_ptrn

  post '/api/v1/objects/include_nested', to: 'intellectual_objects#create_from_json', format: 'json'
  post '/api/v1/objects/:intellectual_object_identifier/files/save_batch', to: 'generic_files#save_batch', format: 'json', intellectual_object_identifier: /[^\/]*/, as: :generic_files_save_batch
  post '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#create', format: 'json', intellectual_object_identifier: /[^\/]*/
  get  '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#index', format: 'json', intellectual_object_identifier: /[^\/]*/

  get  '/api/v1/objects/:identifier', to: 'intellectual_objects#show', format: 'json', identifier: /[^\/]*/, as: :object_by_identifier
  put  '/api/v1/objects/:identifier', to: 'intellectual_objects#update', format: 'json', identifier: /[^\/]*/, as: :object_update_by_identifier
  post '/api/v1/objects/:intellectual_object_identifier/events(.:format)', to: 'events#create', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'events_by_object_identifier'


  get  '/api/v1/file_summary/:intellectual_object_identifier', to: 'generic_files#file_summary', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'file_summary'
  get  '/api/v1/files/not_checked_since', to: 'generic_files#not_checked_since', format: 'json', generic_file_identifier: /[^\/]*/, as: 'files_not_checked_since'
  get  '/api/v1/files/:generic_file_identifier', to: 'generic_files#show', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_by_identifier'
  put  '/api/v1/files/:generic_file_identifier', to: 'generic_files#update', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_update_by_identifier'

  get '/member-api/v1/objects/', to: 'intellectual_objects#api_index', format: 'json'
  get '/member-api/v1/items/', to: 'processed_item#api_index', format: 'json'

  # The pattern for generic_file_identifier is tricky, because we do not want it to
  # conflict with /files/:generic_file_id/events. The pattern is: non-slash characters,
  # followed by a period, followed by more non-slash characters. For example,
  # virginia.edu.bagname/data/file.txt will not conflict with urn:mace:aptrust:12345
  post '/api/v1/files/:generic_file_identifier/events(.:format)', to: 'events#create', format: 'json', generic_file_identifier: /[^\/]*\.[^\/]*/, as: 'events_by_file_identifier'

  #
  # End of API routes
  # ----------------------------------------------------------------------

  Blacklight.add_routes(self)

  mount Hydra::RoleManagement::Engine => '/'

  authenticated :user do
    root to: 'institutions#show', as: 'authenticated_root'
  end

  root :to => 'catalog#index'
end

app/helpers/processed_item_helper.rb
module ProcessedItemHelper

  def current_path(param, value)
    old_path = request.fullpath
    if old_path.include? 'pi_sort'
      new_path = url_for(params.except :pi_sort)
    else
      new_path = old_path
    end
    if new_path.include? '?'
      path = "#{new_path}&#{param}=#{value}"
    else
      path = "#{new_path}?#{param}=#{value}"
    end
    if new_path.include? 'search'
      unless new_path.include? 'qq'
        path = "#{path}&search_field=#{params[:search_field]}&qq=#{params[:qq]}"
      end
    end
    path
  end
end

app/views/processed_item/_facets.html.erb
<div id="facets" class="facets sidenav">
  <h3> Filter:</h3>

  <div id="facet-panel-collapse" class="collapse panel-group">

    <div id="status-parent" class="panel panel-default">
      <div id="filter-title-status" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-status">
        <h5 class="panel-title">Status</h5>
      </div>
      <div id="filter-status" class="panel-collapse facet-content collapse" style="height: 0px;">
        <div class="panel-body">
          <ul class="facet-values list-unstyle">
            <% @statuses.each do |status| %>
                <li>
                  <span class="facet-label"><a href="<%= current_path('status', status) %>" ><%= status %></a></span>
                  <span class="facet-count"><%= @counts[status] %></span>
                </li>
            <% end %>
            <% unless @selected[:status].nil? %>
                <script>selected("status", "<%= @selected[:status] %>", "<%=url_for(params.except :status)%>")</script>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div id="stage-parent" class="panel panel-default">
      <div id="filter-title-stage" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-stage">
        <h5 class="panel-title">Stage</h5>
      </div>
      <div id="filter-stage" class="panel-collapse facet-content collapse" style="height: 0px;">
        <div class="panel-body">
          <ul class="facet-values list-unstyle">
            <% @stages.each do |stage| %>
                <li>
                  <span class="facet-label"><a href="<%= current_path('stage', stage) %>" ><%= stage %></a></span>
                  <span class="facet-count"><%= @counts[stage] %></span>
                </li>
            <% end %>
            <% unless @selected[:stage].nil? %>
                <script>selected("stage", "<%= @selected[:stage] %>", "<%=url_for(params.except :stage)%>")</script>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div id="action-parent" class="panel panel-default">
      <div id="filter-title-action" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-action">
        <h5 class="panel-title">Action</h5>
      </div>
      <div id="filter-action" class="panel-collapse facet-content collapse" style="height: 0px;">
        <div class="panel-body">
          <ul class="facet-values list-unstyle">
            <% @actions.each do |action| %>
                <li>
                  <span class="facet-label"><a href="<%= current_path('item_action', action) %>" ><%= action %></a></span>
                  <span class="facet-count"><%= @counts[action] %></span>
                </li>
            <% end %>
            <% unless @selected[:item_action].nil? %>
                <script>selected("action", "<%= @selected[:item_action] %>", "<%=url_for(params.except :item_action)%>")</script>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <% if current_user.admin? %>
        <div id="institution-parent" class="panel panel-default">
          <div id="filter-title-institution" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-institution">
            <h5 class="panel-title">Institution</h5>
          </div>
          <div id="filter-institution" class="panel-collapse facet-content collapse" style="height: 0px;">
            <div class="panel-body">
              <ul class="facet-values list-unstyle">
                <% @institutions.each do |inst| %>
                    <li>
                      <span class="facet-label"><a href="<%= current_path('institution', inst) %>" ><%= inst %></a></span>
                      <span class="facet-count"><%= @counts[inst] %></span>
                    </li>
                <% end %>
                <% unless @selected[:institution].nil? %>
                    <script>selected("institution", "<%= @selected[:institution] %>", "<%=url_for(params.except :institution)%>")</script>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    <% end %>

    <div class="panel panel-default">
      <script>
          $(".filter_div").toggle()
      </script>
      <div class="panel-heading">
        <h5 class="panel-title">
          <span class="glyphicon glyphicon-remove-circle">
          <%= link_to raw("Remove Filters"), processed_items_path %>
          </span>
        </h5>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">Show Reviewed Items?</h5>
        <input type="checkbox" id="toggleReviewed" onclick="showReviewed()" >
        <script> $("#toggleReviewed").prop('checked', <%= session[:show_reviewed] %>) </script>
      </div>
    </div>

  </div>
</div>

app/views/processed_item/_item_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Etag</th>
    <th>Institution</th>
    <th>Processed</th>
    <th>Action</th>
    <th>Stage</th>
    <th>Status</th>
    <th>Reviewed?</th>
  </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr class="<%= item.status %>">
        <td><% if item.status == Fluctus::Application::FLUCTUS_STATUSES['success'] || item.status == Fluctus::Application::FLUCTUS_STATUSES['fail'] %>
          <input type="checkbox" class="review" name="reviewed" value="reviewed" id="r_<%= item.id %>" >
        <% end %></td>
        <td class="name"><% if item.action == Fluctus::Application::FLUCTUS_ACTIONS['delete'] %>
              <% unless item.generic_file_identifier.nil? %>
                  <a href="<%= processed_item_path(id: item.id) %>" ><%= truncate(item.generic_file_identifier, length: 45) %></a>
              <% else %>
                  <a href="<%= processed_item_path(id: item.id) %>" ><%= truncate(item.object_identifier, length: 45) %></a>
              <% end %>
          <% elsif !item.object_identifier.blank? %>
              <a href="<%= processed_item_path(id: item.id) %>" ><%= truncate(item.object_identifier, length: 45) %></a>
          <% else %>
              <a href="<%= processed_item_path(id: item.id) %>" ><%= truncate(item.name, length: 45) %></a>
          <% end %></td>
        <td class="etag"><%= item.etag %></td>
        <td><%= item.institution %></td>
        <td><%= time_ago_in_words item.date %></td>
        <td><%= item.action %></td>
        <td><%= item.stage %></td>
        <td class="status"><%= item.status %></td>
        <td><%= item.reviewed.to_s.capitalize %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% if (@items.length == 0) %>
    <p>There are no items to display at this time.</p>
<% end %>
<div class="paging">
  <%= paginate @items %>
</div>

app/views/processed_item/_review_items.html.erb
<div class="dropdown pull-right">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Mark ...
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation">
      <%= link_to raw("Selected as Reviewed/Resolve"),
                  '#',
                  {tabindex: -1, role: "menuitem", onclick: "callHandleSelected()"} %>
    </li>
    <li role="presentation">
      <%= button_to raw("All as Reviewed/Resolve"),
                    {:controller => "processed_item", :action => "review_all"},
                    :data => {confirm: "Are you sure you want to mark all items as reviewed?"}  %>
    </li>
  </ul>
</div>

app/views/processed_item/_search_breadcrumb.html.erb
<% unless (params[:qq].nil? || params[:qq] == '') && @selected == {} %>
  <div id="appliedParams" class="clearfix constraints-container">
    <div class="pull-right">
       <a class="catalog_startOverLink btn btn-sm btn-text" href="/itemresults" id="startOverLink">Start Over</a>
    </div>
    <span class="constraints-label">You searched for: </span>
    <% unless params[:qq].nil? || params[:qq] == '' %>
      <span class="btn-group appliedFilter constraint query">
        <span class="constraint-value btn btn-sm btn-default btn-disabled">
          <% if params[:pi_search_field].nil? || params[:pi_search_field] == '' || params[:pi_search_field] == 'All Fields' %>
            <span class="filterValue"><%= params[:qq] %></span>
          <% else %>
            <span class="filterName"><%= params[:pi_search_field] %></span>
            <span class="filterValue"><%= params[:qq] %></span>
          <% end %>
        </span>
        <a class="btn btn-default btn-sm remove" href="<%=url_for(params.except :qq)%>">
          <span class="glyphicon glyphicon-remove"></span>
          <span class="sr-only">Remove constraint <%= params[:qq] %></span>
        </a>
      </span>
    <% end %>
    <% if @selected %>
      <% @selected.each do |key, value| %>
        <span class="btn-group appliedFilter constraint filter">
          <span class="constraint-value btn btn-sm btn-default btn-disabled">
            <span class="filterName"><%= key.capitalize %></span>
            <span class="filterValue"><%= value %></span>
          </span>
          <a class="btn btn-default btn-sm remove" href="<%=url_for(params.except key)%>">
            <span class="glyphicon glyphicon-remove"></span>
            <span class="sr-only">Remove constraint <%= key %>: <%= value %></span>
          </a>
        </span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/processed_item/_search_facets.html.erb
<div id="facets" class="facets sidenav">
  <h3> Filter:</h3>
  <div id="facet-panel-collapse" class="collapse panel-group">

    <div id="status-parent" class="panel panel-default">
      <div id="filter-title-status" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-status">
        <h5 class="panel-title">Status</h5>
      </div>
      <div id="filter-status" class="panel-collapse facet-content collapse" style="height: 0px;">
        <div class="panel-body">
          <ul class="facet-values list-unstyle">
            <% @statuses.each do |status| %>
                <li>
                  <span class="facet-label"><a href="<%= current_path('status', status) %>" ><%= status %></a></span>
                  <span class="facet-count"><%= @counts[status] %></span>
                </li>
            <% end %>
            <% unless @selected[:status].nil? %>
                <script>selected("status", "<%= @selected[:status] %>", "<%=url_for(params.except :status)%>")</script>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div id="stage-parent" class="panel panel-default">
      <div id="filter-title-stage" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-stage">
        <h5 class="panel-title">Stage</h5>
      </div>
      <div id="filter-stage" class="panel-collapse facet-content collapse" style="height: 0px;">
        <div class="panel-body">
          <ul class="facet-values list-unstyle">
            <% @stages.each do |stage| %>
                <li>
                  <span class="facet-label"><a href="<%= current_path('stage', stage) %>" ><%= stage %></a></span>
                  <span class="facet-count"><%= @counts[stage] %></span>
                </li>
            <% end %>
            <% unless @selected[:stage].nil? %>
                <script>selected("stage", "<%= @selected[:stage] %>", "<%=url_for(params.except :stage)%>")</script>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div id="action-parent" class="panel panel-default">
      <div id="filter-title-action" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-action">
        <h5 class="panel-title">Action</h5>
      </div>
      <div id="filter-action" class="panel-collapse facet-content collapse" style="height: 0px;">
        <div class="panel-body">
          <ul class="facet-values list-unstyle">
            <% @actions.each do |action| %>
                <li>
                  <span class="facet-label"><a href="<%= current_path('item_action', action) %>" ><%= action %></a></span>
                  <span class="facet-count"><%= @counts[action] %></span>
                </li>
            <% end %>
            <% unless @selected[:item_action].nil? %>
                <script>selected("action", "<%= @selected[:item_action] %>", "<%=url_for(params.except :item_action)%>")</script>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <% if current_user.admin? %>
        <div id="institution-parent" class="panel panel-default">
          <div id="filter-title-institution" class="collapse-toggle panel-heading collapsed" data-toggle="collapse" data-target="#filter-institution">
            <h5 class="panel-title">Institution</h5>
          </div>
          <div id="filter-institution" class="panel-collapse facet-content collapse" style="height: 0px;">
            <div class="panel-body">
              <ul class="facet-values list-unstyle">
                <% @institutions.each do |inst| %>
                    <li>
                      <span class="facet-label"><a href="<%= current_path('institution', inst) %>" ><%= inst %></a></span>
                      <span class="facet-count"><%= @counts[inst] %></span>
                    </li>
                <% end %>
                <% unless @selected[:institution].nil? %>
                    <script>selected("institution", "<%= @selected[:institution] %>", "<%=url_for(params.except :institution)%>")</script>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    <% end %>

    <div class="panel panel-default">
      <script>
          $(".filter_div").toggle()
      </script>
      <div class="panel-heading">
        <h5 class="panel-title">
          <span class="glyphicon glyphicon-remove-circle">
          <%= link_to raw("Remove Filters"), processed_items_path %>
          </span>
        </h5>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">Show Reviewed Items?</h5>
        <input type="checkbox" id="toggleReviewed" onclick="showReviewed()" >
        <script> $("#toggleReviewed").prop('checked', <%= session[:show_reviewed] %>) </script>
      </div>
    </div>

  </div>
</div>

app/views/processed_item/_search_form.html.erb
<%= form_tag action: 'search', method: :get, class: 'search-query-form form-inline clearfix', controller: "processed_item" do %>
    <div class="input-group">

      <span class="input-group-addon">
        <label for="search_field" class="sr-only">Processed Item Search</label>
        <%= select_tag(:search_field, options_for_select(['All Fields', 'Name', 'Etag'], h(params[:search_field])), :class=>"search_field") %>
        </span>
      <label for="q" class="sr-only">Search Box</label>
      <%= text_field_tag :qq, params[:qq], :placeholder => 'Search...', :class => "search_q q form-control", :id => "qq", :autofocus => should_autofocus_on_search_box? %>

      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary search-btn" id="pi_search">
          <span class="submit-search-text">Search</span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
        </span>
    </div>
<% end %>

app/views/processed_item/_sort_and_per_page.html.erb
<div id="sortAndPerPage">
  <div class="page_links">
    <span class="page_entries">
       <strong><%= @first_number %></strong> - <strong><%= @second_number %></strong> of <strong><%= @total_number %></strong>
    </span>
  </div>
  <% if current_user.admin? || current_user.institutional_admin? %>
      <%= render 'review_items' %>
  <% end %>
  <div class="search-widgets pull-right">
    <div id="sort-dropdown" class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <a href="#">Sort by </a>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><a href="<%= current_path('pi_sort', 'date') %>">Processed Date</a></li>
        <li><a href="<%= current_path('pi_sort', 'name') %>">Name</a></li>
        <% if current_user.admin? %>
          <li><a href="<%= current_path('pi_sort', 'institution') %>">Institution</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/processed_item/handle_selected.js.erb
$(window).scrollTop(0);
location.reload();

app/views/processed_item/index.html.erb
<div id="sidebar" class="col-md-3">
  <%= render 'facets' %>
</div>

<div id="content" class="col-md-9">
  <section>
    <%= render 'search_breadcrumb' %>
  </section>
  <section>
    <%= render 'sort_and_per_page' %>
  </section>
  <section id="itemTable" class="queue">
    <%= render 'item_table' %>
  </section>
</div>

app/views/processed_item/search.html.erb
<div id="sidebar" class="col-md-3">
  <%= render 'search_facets' %>
</div>

<div id="content" class="col-md-9">
  <section>
    <%= render 'search_breadcrumb' %>
  </section>
  <section>
    <%= render 'sort_and_per_page' %>
  </section>
  <section id="itemTable" class="queue">
    <%= render 'item_table' %>
  </section>
</div>

app/views/processed_item/show_reviewed.js.erb
$(window).scrollTop(0);
location.reload();